dist: bionic
before_install:
  - wget https://github.com/assimp/assimp/archive/v5.0.0.tar.gz
  - tar xvf v5.0.0.tar.gz
  - pushd assimp-5.0.0 && cmake CMakeLists.txt -G 'Unix Makefiles' && make && popd
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$PWD/assimp-5.0.0/lib
  - pip install coverage
language: python
python:
  - "3.7"
script:
  - './.travis/travis-ci.sh'
