dist: xenial
before_install:
  - wget https://github.com/assimp/assimp/archive/v4.1.0.tar.gz
  - tar xvf v4.1.0.tar.gz
  - pushd assimp-4.1.0 && cmake CMakeLists.txt -G 'Unix Makefiles' && make && popd
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$PWD/assimp-4.1.0/lib
language: python
python:
  - "3.5"
script:
  - './.travis/travis-ci.sh'
