# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Build Models

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install COLLADA2GLTF
      run: |
        mkdir COLLADA2GLTF
        pushd COLLADA2GLTF
        wget https://github.com/KhronosGroup/COLLADA2GLTF/releases/download/v2.1.5/COLLADA2GLTF-v2.1.5-linux.zip
        unzip COLLADA2GLTF-v2.1.5-linux.zip
        popd
    - name: Install model sources
      run: |
        mkdir MODEL_SRC
        pushd MODEL_SRC
        wget https://github.com/AuScope/geomodel-2-3dweb/releases/download/PORTAL_RELEASE_20210718/GEOMODELS_SRC-GA.tar.gz
        tar xvfz GEOMODELS_SRC-GA.tar.gz
        popd
    - name: Install pdm
      run: |
        python -m pip install --upgrade pip
        pip install pdm
    - name: Install dependencies
      run: |
        pdm install
    - name: Build
      run: |
        export COLLADA2GLTF_BIN=`pwd`/COLLADA2GLTF
        echo "COLLADA2GLTF_BIN=$COLLADA2GLTF_BIN"
        export GEOMODELS_HOME=`pwd`/MODEL_SRC
        echo "GEOMODELS_HOME=$GEOMODELS_HOME"
        eval $(pdm venv activate)
        cd web_build/
        ./batch_proc.py

