# Release web assets from the latest successful build action into a certain release
name: Release Models Backend

on: 
  workflow_dispatch:
    inputs:
      rel_tag:
        description: Files are inserted into the release with this tag
        type: string
        required: false
        default: PORTAL_RELEASE_20210718

jobs:
  do-release:
    runs-on: ubuntu-latest
    steps:
    - name: Download artifacts
      uses: dawidd6/action-download-artifact@v6
      with:
        workflow: build_models_backend.yml
        workflow_conclusion: success
        branch: master
    - name: Add to release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{inputs.rel_tag}}
        name: Source and web asset release based on tag ${{inputs.rel_tag}}
        files: ./**/*.tar.gz
        fail_on_unmatched_files: true
