# Upon detection of new release tag, this action:
#
# 1. Creates a backend backend release
# 2. Adds the files from the latest successful API build action
#
# NB: After running this release the 'release_models.yml' action should be ran to add 
# model files to backend build and create a docker build 
#
name: Release API Backend

on:
  push:
    tags:
      - "PORTAL_RELEASE_*"

jobs:
  do-release:
    runs-on: ubuntu-latest
    steps:
    - name: Download artifacts
      uses: dawidd6/action-download-artifact@v6
      with:
        workflow: build_api_backend.yml
        workflow_conclusion: success
        branch: master
    - name: List files
      run: |
          ls -al
    - name: Add to release
      uses: softprops/action-gh-release@v2
      with:
        name: AuScope Geomodels back-end assets release based on tag ${{github.ref}}
        files: |
              ./**/*.tar.gz
              ./py_pkg_state
        fail_on_unmatched_files: true
